### ISSUE TITLE
./run-tests.sh -v all dumps code

### ISSUE THREAD

**Issue by fuzzy** [major0/shlib#3]
./run-tests.sh -v runs in trace mode, would be more appropriately named -d (debug)

**Comment by major0** [comment]
Yah, this is running in `set -v` mode, which prints everything being read into the parser... which is a lot when sourcing files... certainly not appropriate for a verbose flag ..

**Comment by major0** [comment]
Curiously, the `--help` output also lists `--verbose` which isn't even supported. Removed `-v` and `--verbose` support for now in 029c255bf13fa14add2c760e763a9635e31922f0 as we have a `-x` option already which enables tracing of script execution.  Will revisit adding `-v` later should it ever prove to be useful.
